version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing app dependencies...
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.25.7/2023-03-17/bin/windows/amd64/kubectl
      - chmod +x ./kubectl
      - kubectl version --short --client
      - npm install cypress-cucumber-preprocessor
      - npm install multiple-cucumber-html-reporter
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
  
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
      - kubectl config view --minify
      - URL='http://'$(kubectl get ingress -n beta-app ingress-mystays --output jsonpath={.status.loadBalancer.ingress[0].hostname})
      - echo $URL

  build:
    commands:
      - echo Test execution starts...
      - npx cypress run --env awsurl=$URL
  post_build:
    commands:
      - echo Test execution report generation...
      - node cucumberHTMLReport.js
      - ls cypress/reports
      - aws s3 cp cypress/reports/ s3://ibs-skillset-happystays-automation/ExecutionReport/ --recursive
